# -*- coding: utf-8 -*-
"""
Evidence chain generation for DeepAlpha event clusters.

Input: event objects generated by event_cluster.py.
Output: structured JSON-ready evidence chains for future AI report modules.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


OFFICIAL_HINTS = {
    "whitehouse", "potus", "realdonaldtrump", "federalreserve", "ecb",
    "ksamofaen", "idf", "defenceu", "kremlin", "pentagon", "ustreasury",
}
WIRE_HINTS = {
    "reuters", "bloomberg", "wsj", "cnbc", "financialtimes", "ap", "bbc",
    "axios",
}
JOURNALIST_HINTS = {
    "javierblas", "jkempenergy", "richardengel", "samdagher", "jackdetsch",
    "sangernyt", "oil_sheppard", "rory_johnston", "clydecommods",
}


def build_evidence_chains(events: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [build_evidence_chain(event) for event in events]


def build_evidence_chain(event: dict[str, Any]) -> dict[str, Any]:
    evidences = [build_evidence(tweet) for tweet in event.get("related_tweets", [])]
    evidences = [evidence for evidence in evidences if evidence is not None]
    source_types = sorted({item["source_type"] for item in evidences})
    source_count = len({item["source_account"] for item in evidences if item["source_account"]})

    return {
        "event_id": event.get("event_id"),
        "event_title": event.get("event_title"),
        "first_seen_time": event.get("first_seen_time"),
        "last_seen_time": event.get("last_seen_time"),
        "source_count": source_count,
        "source_types": source_types,
        "multi_source_status": classify_multi_source(source_count, source_types),
        "evidence_count": len(evidences),
        "average_credibility": average_credibility(evidences),
        "evidence": evidences,
    }


def build_evidence(tweet: dict[str, Any]) -> dict[str, Any] | None:
    content = first_value(tweet, ("content", "text", "full_text", "body"))
    if not content:
        return None

    account = normalize_account(first_value(tweet, ("handle", "account", "username", "user", "source")))
    source_type = classify_source_type(account)
    credibility = account_credibility_score(account)

    return {
        "source_account": account,
        "source_type": source_type,
        "published_time": to_iso(parse_datetime(first_value(tweet, ("timestamp", "created_at", "time")))),
        "collected_time": to_iso(parse_datetime(first_value(tweet, ("collected_at", "saved_at", "scraped_at")))),
        "summary": summarize_text(str(content)),
        "url": first_value(tweet, ("tweet_link", "url", "link")),
        "credibility_score": credibility,
    }


def classify_multi_source(source_count: int, source_types: Iterable[str]) -> str:
    types = set(source_types)
    has_strong_source = bool(types & {"官方", "通讯社"})
    if source_count >= 3 and has_strong_source:
        return "strong_multi_source"
    if source_count >= 2:
        return "initial_multi_source"
    return "single_source"


def account_credibility_score(account: str | None) -> int:
    from deepalpha.x_intel_rules import get_accounts_by_level

    normalized = normalize_account(account)
    if not normalized:
        return 2

    level_scores = {"S": 10, "A": 8, "B": 6, "C": 4}
    for level, score in level_scores.items():
        accounts = {normalize_account(item).lower() for item in get_accounts_by_level(level)}
        if normalized.lower() in accounts:
            return score
    return 2


def classify_source_type(account: str | None) -> str:
    normalized = normalize_account(account)
    if not normalized:
        return "普通账号"

    key = normalized.lower().lstrip("@")
    if key in OFFICIAL_HINTS:
        return "官方"
    if key in WIRE_HINTS:
        return "通讯社"
    if key in JOURNALIST_HINTS:
        return "记者"

    from deepalpha.x_intel_rules import get_accounts_by_group

    oil_accounts = {normalize_account(item).lower() for item in get_accounts_by_group("oil")}
    if normalized.lower() in oil_accounts:
        return "分析师"
    return "普通账号"


def average_credibility(evidences: list[dict[str, Any]]) -> float:
    if not evidences:
        return 0.0
    total = sum(float(item.get("credibility_score", 0)) for item in evidences)
    return round(total / len(evidences), 2)


def summarize_text(text: str, limit: int = 180) -> str:
    compact = " ".join(text.split())
    if len(compact) <= limit:
        return compact
    return compact[: limit - 3].rstrip() + "..."


def parse_datetime(value: Any) -> datetime | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return ensure_aware(value)
    text = str(value).strip()
    if not text:
        return None
    if text.endswith("Z"):
        text = text[:-1] + "+00:00"
    try:
        return ensure_aware(datetime.fromisoformat(text))
    except ValueError:
        return None


def to_iso(value: datetime | None) -> str | None:
    return value.isoformat() if value else None


def ensure_aware(value: datetime) -> datetime:
    if value.tzinfo is None:
        return value.replace(tzinfo=timezone.utc)
    return value.astimezone(timezone.utc)


def normalize_account(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    if not text.startswith("@"):
        text = f"@{text}"
    return text


def first_value(raw: dict[str, Any], fields: Iterable[str]) -> Any:
    for field_name in fields:
        value = raw.get(field_name)
        if value is not None and str(value) != "nan":
            return value
    return None


def load_events(path: str | Path) -> list[dict[str, Any]]:
    with Path(path).open("r", encoding="utf-8") as f:
        data = json.load(f)
    if isinstance(data, list):
        return [item for item in data if isinstance(item, dict)]
    if isinstance(data, dict) and isinstance(data.get("events"), list):
        return [item for item in data["events"] if isinstance(item, dict)]
    raise ValueError("Input JSON must be a list of events or an object with an events list")


def sample_events() -> list[dict[str, Any]]:
    from deepalpha.event_cluster import cluster_events, sample_cleaned_tweets

    return cluster_events(sample_cleaned_tweets())


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate evidence chains from event clusters")
    parser.add_argument("--input", help="JSON file containing event_cluster.py output")
    parser.add_argument("--pretty", action="store_true", help="Pretty-print JSON output")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    events = load_events(args.input) if args.input else sample_events()
    chains = build_evidence_chains(events)
    indent = 2 if args.pretty else None
    print(json.dumps(chains, ensure_ascii=False, indent=indent))


if __name__ == "__main__":
    main()
